import { createHash } from "node:crypto";
import { FieldValue, Timestamp, getFirestore, type Firestore } from "firebase-admin/firestore";
import { getAuth } from "firebase-admin/auth";
import { getStorage } from "firebase-admin/storage";
import { onSchedule } from "firebase-functions/v2/scheduler";
import { onDocumentCreated } from "firebase-functions/v2/firestore";

export const GRACE_PERIOD_MS = Number(process.env.ACCOUNT_DELETION_GRACE_MS ?? 7 * 24 * 60 * 60 * 1000);
export const LEASE_MS = 5 * 60 * 1000; export const MAX_ATTEMPTS = 5;
const hash = (uid: string) => createHash("sha256").update(uid).digest("hex").slice(0, 16);
export const backoffMs = (n: number) => Math.min(3600000, 30000 * 2 ** Math.max(0,n-1));
export const canClaimDeletion = (d: any, now = Date.now()) => (d.status === "scheduled" || d.status === "retryable_failed") && (!d.nextAttemptAt || d.nextAttemptAt.toMillis() <= now) || d.status === "processing" && (!d.leaseExpiresAt || d.leaseExpiresAt.toMillis() <= now);
export type DeletionTestAdapter = { deletePrefix?: (uid:string)=>Promise<number>; deleteAuth?:(uid:string)=>Promise<void>; observe?:(step:string)=>void };
async function audit(db: Firestore, uid: string, step: string, status: string, attempt: number, summary: Record<string,number> = {}) { await db.collection("accountDeletionAudit").add({ uidHash:hash(uid), processorVersion:"1", step,status,attempt,summary,at:FieldValue.serverTimestamp() }); }
async function deletePrefix(uid:string):Promise<number>{ const bucket=getStorage().bucket(); const [files]=await bucket.getFiles({prefix:`profilePhotos/${uid}/`}); await Promise.all(files.map(f=>f.delete({ignoreNotFound:true}))); return files.length; }
export async function processDeletion(uid:string, db=getFirestore(), adapter?:DeletionTestAdapter):Promise<void>{ const ref=db.doc(`accountDeletionRequests/${uid}`); let d:any; await db.runTransaction(async tx=>{const s=await tx.get(ref); if(!s.exists||s.data()!.uid!==uid||!canClaimDeletion(s.data())) return; d=s.data(); tx.update(ref,{status:"processing",leaseOwner:"worker",leaseExpiresAt:Timestamp.fromMillis(Date.now()+LEASE_MS),processingStartedAt:FieldValue.serverTimestamp()});}); if(!d)return; const attempt=(d.attemptCount??0)+1; try { adapter?.observe?.("tokens"); const tokens=await db.collection(`users/${uid}/pushTokens`).get(); await Promise.all(tokens.docs.map(x=>x.ref.set({enabled:false,token:FieldValue.delete(),invalidatedAt:FieldValue.serverTimestamp(),invalidReason:"account_deleted"},{merge:true}))); adapter?.observe?.("outbox"); await db.collection("notificationOutbox").where("recipientUid","==",uid).get().then(s=>Promise.all(s.docs.filter(x=>x.data().status!=="sent").map(x=>x.ref.set({status:"skipped",terminalReason:"account_deleted"},{merge:true})))); adapter?.observe?.("storage"); const images=await (adapter?.deletePrefix?.(uid) ?? deletePrefix(uid)); await db.doc(`profiles/${uid}`).delete(); adapter?.observe?.("blocks"); await db.collection("blocks").get().then(s=>Promise.all(s.docs.filter(x=>x.id.startsWith(uid+"_")||x.id.endsWith("_"+uid)).map(x=>x.ref.delete()))); await audit(db,uid,"data_cleanup","completed",attempt,{tokens:tokens.size,images}); await ref.update({status:"completed",completedAt:FieldValue.serverTimestamp(),leaseExpiresAt:null,attemptCount:attempt,steps:{tokens:"completed",outbox:"completed",storage:"completed",profile:"completed",auth:"completed"}}); adapter?.observe?.("auth"); try{if(adapter?.deleteAuth)await adapter.deleteAuth(uid);else await getAuth().deleteUser(uid);}catch(e:any){if(e?.code!=="auth/user-not-found")throw e;} await audit(db,uid,"completion","completed",attempt); }catch(e:any){const terminal=attempt>=MAX_ATTEMPTS; await ref.set({status:terminal?"permanently_failed":"retryable_failed",attemptCount:attempt,nextAttemptAt:Timestamp.fromMillis(Date.now()+backoffMs(attempt)),lastErrorCode:"processor_failure",lastErrorAt:FieldValue.serverTimestamp(),leaseExpiresAt:null},{merge:true}); await audit(db,uid,"processor",terminal?"permanently_failed":"retryable_failed",attempt);}}
export const processAccountDeletionRequests=onSchedule("every 5 minutes",async()=>{const db=getFirestore();const s=await db.collection("accountDeletionRequests").where("status","in",["scheduled","retryable_failed","processing"]).limit(100).get();await Promise.all(s.docs.map(x=>processDeletion(x.id,db)));});
export const scheduleAccountDeletionRequest=onDocumentCreated("accountDeletionRequests/{uid}",async event=>{const d=event.data?.data() as any;if(!d||d.uid!==event.params.uid||d.status!=="requested")return;await event.data!.ref.update({status:"scheduled",scheduledFor:Timestamp.fromMillis(Date.now()+GRACE_PERIOD_MS),nextAttemptAt:Timestamp.fromMillis(Date.now()+GRACE_PERIOD_MS)});});
